version: '3.7'
services:
  kasper-app:
    image: node:16.15.1
    command: yarn start
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3333:3333
      - 4200:4200
    depends_on:
      - kasper-db

  kasper-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 84pUi@6EeMFg
      MYSQL_USER: kirk
      MYSQL_PASSWORD: 4^jmSJ86cp!z
      MYSQL_DATABASE: kasper_development
    volumes:
      - ./docker_db/mount:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
