version: "3.7"
services:
  backend-app:
    container_name: backend-app
    build:
      context: ./
      cache_from:
        - my-base-image:nx-base
      dockerfile: ./apps/backend-app/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    image: backend-app:nx-dev
    ports:
      - 3333:3333
    environment:
      NODE_ENV: "development"
      PORT: 3333
      DATABASE_URL: mysql://root:84pUi@6EeMFg@kasper-db:3306/kasper_development?schema=public
    networks:
      - corp
    restart: on-failure
    depends_on:
      - kasper-db

  frontend-app:
    container_name: frontend-app
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/frontend-app/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    image: frontend-app:nx-dev
    ports:
      - 4900:80
    environment:
      NODE_ENV: "development"
      PORT: 4900
    networks:
      - corp
    restart: on-failure

  kasper-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 84pUi@6EeMFg
      MYSQL_DATABASE: kasper_development
    volumes:
      - ./docker_db/mount:/var/lib/mysql
    networks:
      - corp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - corp
networks:
  corp:
    driver: bridge
